### ISSUE TITLE
Default rails Dockerfile should contain bundle exec rake

### ISSUE THREAD

**Issue by paulca** [convox/ruby#2]
The default Dockerfile contains the line:

`RUN rake assets:precompile`

...to avoid a conflict with any system-installed rake, it should probably be:

`RUN bundle exec rake assets:precompile`

**Comment by ianmalott** [comment]
@paulca thanks for the extra eyes. Not seeing that line in this Dockerfile, though. Were you maybe looking at github.com/convox-examples/rails? I see a relevant line in that repo if you'd like to move your issue there.

https://github.com/convox-examples/rails/blob/master/Dockerfile#L15
